version: '3.8'
networks:
  backend:

services:
  api:
    container_name: api
    networks:
      - backend
    image: soohyeok8901/madeit:dev-api-1.0.0
    ports:
      - "8901:8901"
    restart: always

  nginx:
    networks:
      - backend
    container_name: nginx
    image: nginx:1.21-alpine
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    networks:
      - backend
    container_name: certbot
    image: certbot/certbot:v0.36.0
    # restart: always
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"