name: Dockerize dev server

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: [ self-hosted, madeit-dev ]

    steps:
    - 
      uses: actions/checkout@v2
    -   
      name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - 
      name: Run Scripts for Dockerizing
      run: |
        cd /home/docker-compose
        docker-compose down
        export TAG=dev-api-0.2.0
        docker-compose up -d
    -
      name: Run Scripts for remove docker image 
      run: docker rmi -f soohyeok8901/madeit:dev-api-0.1.0
     
