name: Dockerize dev server

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: [ self-hosted, madeit-dev ]

    steps:
    - 
      uses: actions/checkout@v2
      if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    -   
      name: Login to Dockerhub
      if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - 
      name: Run Scripts
      if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
      run: |
        docker-compose down
        cd /home/docker-compose
        export TAG=dev-api-0.0.1
        docker-compose up
     
