name: Dockerize prod server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: [ self-hosted, madeit-prod ]

    steps:
    - 
      uses: actions/checkout@v2
    -   
      name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - 
      name: Run Scripts for Dockerizing
      run: |
        cd /home/docker-compose
        docker-compose down
        export TAG=prod-api-0.2.29
        docker-compose up -d
      
    # - # 잘 확인
    #   name: Run Scripts for remove docker image 
    #   run: docker rmi -f soohyeok8901/madeit:prod-api-0.2.16
     
